### ISSUE TITLE
no metdata

### ISSUE THREAD

**Issue by bert1475** [WaypointRP/wp-printer#3]
![image](https://github.com/WaypointRP/wp-printer/assets/51228862/f580da4a-e215-4476-ab12-0b1cb426bc46)

i don't know how to fix, but i think you're missing a file

**Comment by BackSH00TER** [comment]
There is no such metadata file in this resource.
If anything this error is talking about the fxmanifest file. 

@bert1475 Did you make any modifications to the script?
